# Generated by Django 2.2.13 on 2024-08-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbpl',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
