# Generated by Django 2.2.13 on 2024-08-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240812_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbpl',
            new_name='symbol',
        ),
    ]
